name: Cypress Action Guide
description: Runs Cypress tests

on: push 

jobs: 
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
         -  name: Chekout
            uses: actions/checkout@v4
         -  name: Cypress run
            uses: cypress-io/githun-action@v6
            with:
                start: npm run cypressTest
